import { Geist, Geist_Mono } from "next/font/google";

import styles from "./styles.module.css";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const owner = process.env.OWNER;
  const repo = process.env.REPO;
  const token = process.env.GITHUB_PAT;

  const contributorsListRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/forks`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github.v3+json",
    },
  })

  const contributorsList = await contributorsListRes.json();

  // console.log(contributorsList, "***************  contributorsList  *****************");


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={styles.viewPortWrapper}>
        <div className={styles.headerContainer}>Header</div>
        <div className={styles.layoutContainer}>
          <div className={styles.sideBarContainer}>
            <div className={styles.searchBarWrapper}>
              <input className={styles.inputBox} />
            </div>
            <div className={styles.contributorsListContainer}>
              <div className={styles.contributorsList}>
                {
                  contributorsList.map((contributor)=>(
                    <span key={contributor.id}>{contributor.owner.login}</span>
                  ))
                } 
              </div>
            </div>
          </div>
          {children}
        </div>
        </div>

      </body>
    </html>
  );
}
